### ISSUE TITLE
When with DynamoDB, login fails after API token expires

### ISSUE THREAD

**Issue by daigotanaka** [daigotanaka/mern-cljs#1]
Error message:

```
Error: ConditionalCheckFailedException: The conditional request failed
    at mern_utils$passport$strategy$except (/Users/daigo/kobo5/selquote/app/www/target/mern_utils/passport/strategy.cljs:55:10)
    at mern_utils.passport.strategy.upsert_record.mern_utils.db.upsert.call.G__23805__delegate (/Users/daigo/kobo5/selquote/app/www/target/mern_utils/passport/strategy.cljs:60:25)
    at mern_utils.passport.strategy.upsert_record.mern_utils.db.upsert.call.G__23805 (/Users/daigo/kobo5/selquote/app/www/target/mern_utils/passport/strategy.cljs:59:25)
    at /Users/daigo/kobo5/selquote/app/www/node_modules/dynamoose/node_modules/q/q.js:1891:17
    at flush (/Users/daigo/kobo5/selquote/app/www/node_modules/dynamoose/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
```

**Comment by daigotanaka** [comment]
Fix:
https://github.com/daigotanaka/mern-cljs/commit/0a7533af85c0cfe0c42477ed7e2af0fcf4cc37b9
